#!/bin/bash

PRODUCT_DIR="__PRODUCT_DIR__"

mv -f "${PRODUCT_DIR}/iWebIT" "${PRODUCT_DIR}/iWebIT.app"
mv -f "${PRODUCT_DIR}/iWebITAgent" "${PRODUCT_DIR}/iWebITAgent.app"

mv -f "${PRODUCT_DIR}/com.rdfonseca.iWebITSysTray.plist" "/Library/LaunchAgents/com.rdfonseca.iWebITSysTray.plist"
mv -f "${PRODUCT_DIR}/com.rdfonseca.iWebITService.plist" "/Library/LaunchDaemons/com.rdfonseca.iWebITService.plist"
chown root "/Library/LaunchDaemons/com.rdfonseca.iWebITService.plist"

mkdir "${PRODUCT_DIR}/Logs"
chmod -R 777 "${PRODUCT_DIR}/Logs"

launchctl load /Library/LaunchDaemons/com.rdfonseca.iWebITService.plist

su - $(basename $HOME) -c 'launchctl load /Library/LaunchAgents/com.rdfonseca.iWebITSysTray.plist'

UPDATE_SIGNAL_PATH="${PRODUCT_DIR}/UPDATE"

if [ ! -f "${UPDATE_SIGNAL_PATH}" ]
then
    open "${PRODUCT_DIR}/iWebIT.app"
fi

exit 0
